spring:
  security:
    filter:
      order: 10
  datasource:
    url: jdbc:postgresql://localhost:5432/senebank
    username: postgres
    password: 123
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        ddl-auto: validate
        default_schema: public

security:
  secret-key: 0630f070-a29d-4e79-a9f0-36fee6cbb666